version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - API_URL=http://server:8080
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=123
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: