version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - API_URL=http://server:8080
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"